In [14]:
from ultralytics import YOLO
import cv2

In [15]:
model = YOLO("yolov8l.pt") 
class_names=model.names
class_names

{0: 'person',
 1: 'bicycle',
 2: 'car',
 3: 'motorcycle',
 4: 'airplane',
 5: 'bus',
 6: 'train',
 7: 'truck',
 8: 'boat',
 9: 'traffic light',
 10: 'fire hydrant',
 11: 'stop sign',
 12: 'parking meter',
 13: 'bench',
 14: 'bird',
 15: 'cat',
 16: 'dog',
 17: 'horse',
 18: 'sheep',
 19: 'cow',
 20: 'elephant',
 21: 'bear',
 22: 'zebra',
 23: 'giraffe',
 24: 'backpack',
 25: 'umbrella',
 26: 'handbag',
 27: 'tie',
 28: 'suitcase',
 29: 'frisbee',
 30: 'skis',
 31: 'snowboard',
 32: 'sports ball',
 33: 'kite',
 34: 'baseball bat',
 35: 'baseball glove',
 36: 'skateboard',
 37: 'surfboard',
 38: 'tennis racket',
 39: 'bottle',
 40: 'wine glass',
 41: 'cup',
 42: 'fork',
 43: 'knife',
 44: 'spoon',
 45: 'bowl',
 46: 'banana',
 47: 'apple',
 48: 'sandwich',
 49: 'orange',
 50: 'broccoli',
 51: 'carrot',
 52: 'hot dog',
 53: 'pizza',
 54: 'donut',
 55: 'cake',
 56: 'chair',
 57: 'couch',
 58: 'potted plant',
 59: 'bed',
 60: 'dining table',
 61: 'toilet',
 62: 'tv',
 63: 'laptop',
 64: 'mou

In [16]:
image_path="people images.jpeg"


In [17]:
image=cv2.imread(image_path)
image=cv2.resize(image,(800,800))
count=0
results=model(image)
for result in results:

    for box in result.boxes:
        #print(box)
        x1, y1, x2, y2 = map(int, box.xyxy[0])
        cv2.rectangle(image, 
                      (x1,y1), 
                      (x2,y2),
                      (255, 255, 0),  
                      12) 

        class_id = int(box.cls)  
        object_name = model.names[class_id]
        if object_name=="person":
            count+=1
        #print(f"object name is {object_name}") 
        cv2.putText(image,f"{object_name}",((x1+x2)//2,(y1+y2)//2), cv2.FONT_HERSHEY_SIMPLEX, 0.5,(255,0,255),1)
        
      
    cv2.imshow("detected_image",image)
    k=cv2.waitKey(0)
    if k==27:
        break
cv2.destroyAllWindows()
print(count)
        


0: 640x640 5 persons, 1213.9ms
Speed: 6.6ms preprocess, 1213.9ms inference, 1.8ms postprocess per image at shape (1, 3, 640, 640)
5


In [18]:
image_path="yolo test image.png"

In [19]:
image=cv2.imread(image_path)
results=model(image)
for result in results:

    boxes=result.boxes.xywh.cpu().numpy()
    for box in boxes:
        print(box)
        x, y, w, h = map(int, box) 
        cv2.rectangle(image, 
                      (x - w//2, y - h//2), 
                      (x + w//2, y + h//2),
                      (255, 255, 0),  
                      3) 
    cv2.imshow("detected_image",image)
    k=cv2.waitKey(0)
    if k==27:
        break
cv2.destroyAllWindows()
        

0: 480x640 1 cup, 1 chair, 1 book, 3 scissorss, 943.1ms
Speed: 16.0ms preprocess, 943.1ms inference, 1.4ms postprocess per image at shape (1, 3, 480, 640)
[     358.79      112.75      174.13         210]
[     710.71      272.86      288.21      135.52]
[     176.89       425.5      293.46      364.98]
[     763.37      456.61       278.1      165.12]
[     487.47      437.99      55.498      275.15]
[     465.38      17.874      338.52      35.749]


In [24]:
model=YOLO("yolov8n.pt")
cap = cv2.VideoCapture("vtest.avi")

cap.set(cv2.CAP_PROP_FRAME_WIDTH, 500)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 500)
cap.set(cv2.CAP_PROP_FPS, 20)
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break
    
    frame = cv2.resize(frame, (500, 500))
    results = model.track(
        frame, 
        persist=True,
        iou=0.8,  
        conf=0.5,
        device='cpu', 
        half=False,  
        verbose=False 
    )

    count = 0
    for result in results:
        for box in result.boxes:
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            
            cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 0, 0), 2)
            
            class_id = int(box.cls)
            object_name = model.names[class_id]
            
            if object_name == "person":
                count += 1

                track_id = int(box.id) if box.id is not None else -1
                
                label = f"Person {track_id}"
                cv2.putText(frame, label, (x1, y1 - 10), 
                            cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)

    cv2.imshow("People Tracking", frame)
    k = cv2.waitKey(1)
    if k == 27: 
        break

cv2.destroyAllWindows()
print(f"عدد الأشخاص المكتشفين: {count}")

عدد الأشخاص المكتشفين: 4
